### ISSUE TITLE
An Firmware Update for the latest Home Assistant Version

### ISSUE THREAD

**Issue by FoxXxHater** [athom-tech/Sound-Reactive-WLED#3]
I cant use my WLED on my Home Assistant because the firmware is to old.

![image](https://github.com/user-attachments/assets/1e1aa723-51d4-4d2d-a149-4b563069c514)

We need an Update, quick, please

**Comment by kazuyoshifunaki** [comment]
I have the same problem. My Athom WLED Sound Reactive controller doesn't work with HA anymore.

**Comment by tarontop** [comment]
This is the latest firmware

https://github.com/athom-tech/WLED/releases/download/0.14.4/Athom_Sound_Reactive_Controller.bin

**Comment by FoxXxHater** [comment]
Okay... i used the official one, from WLED it self
